/* Line icons used by the UI. Both use currentColor so CSS controls the colour.
   Exposed as window.ICONS (name -> SVG markup string).

   The UI is deliberately text-led: badges, category headers and system tags are
   plain labels, so the only icons left are the copy-button pair. Body imagery
   is generated by portraits.js instead. */
window.ICONS = {
  copy: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
    <rect x="9" y="9" width="11" height="11" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>`,

  check: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    <path d="M5 12.5l4.5 4.5L19 6.5"/></svg>`,
};
